- id: sphinx-apidoc
  name: Update Sphinx Documentation
  description: Fails, if documentation is not complete and updates the sphinx doc.
  entry: sphinx_pre_commit
  args: [--force, --no-toc, -o, docs, src]
  always_run: true
  files: '^$'
  pass_filenames: false
  language: python
  additional_dependencies: [sphinx]