- id: sphinx-apidoc
  name: Update Sphinx Documentation
  description: Fails, if documentation is not complete and updates the sphinx doc.
  entry: hook.sh
  args: [--force, --no-toc, -o docs, src]
  always_run: true
  files: '^$'
  pass_filenames: false
  language: script

- id: activate-venv
  name: Activate venv
  description: Activate the virtual environment
  entry: run_command.sh
  args: [.venv\Scripts\activate]
  always_run: true
  files: '^$'
  pass_filenames: false
  language: script