[project]
name = "sphinx_pre_commit"
version = "1.0.0"

[project.scripts]
sphinx_pre_commit = "sphinx_pre_commit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"